# Generated by Django 4.1.7 on 2023-06-04 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Posts', '0003_alter_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Blog_Posts.post'),
            preserve_default=False,
        ),
    ]
