# Generated by Django 4.1.7 on 2023-06-05 20:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog_Posts', '0004_remove_post_comments_comment_commented_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEdit',
            new_name='EditUser',
        ),
    ]
